all:
  children:
    source_control:
      hosts:
        cp-a-1:
          ansible_host: 10.10.10.11
          mysql_defaults_file: /root/.my.cnf
          openrc_file: /root/admin-openrc-source.sh
    target_control:
      hosts:
        cp-b-1:
          ansible_host: 10.20.10.11
          mysql_defaults_file: /root/.my.cnf
          openrc_file: /root/admin-openrc-target.sh
    target_reference_compute:
      hosts:
        cp-b-compute-reference:
          ansible_host: 10.20.20.21
    rehome_compute:
      hosts:
        compute-023:
          ansible_host: 10.30.20.23
          rehome_host: compute-023
          hypervisor_hostname: compute-023
